# Generated by Django 5.1.4 on 2025-01-24 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadet', '0003_role_user_delete_cadet_delete_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('intra_id', models.CharField(max_length=60)),
                ('project_id', models.IntegerField()),
                ('presence_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_intra_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='cadet.userintra'),
        ),
    ]
