# Generated by Django 5.1.4 on 2025-01-24 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadet', '0004_userintra_user_user_intra_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField(blank=True)),
                ('title', models.CharField(max_length=60)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('work_type', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('location_type', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('title_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_experience', to='cadet.worktitle')),
            ],
        ),
    ]
