# Generated by Django 5.1.4 on 2025-01-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadet', '0005_worktitle_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_work_experience', to='cadet.workexperience'),
        ),
    ]
